"""initial_stroma_schema

Revision ID: 03852c0b6ea3
Revises: 
Create Date: 2026-05-16 06:25:00.582459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03852c0b6ea3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.String(length=100), nullable=False),
    sa.Column('assessment_date', sa.Date(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'assessment_date', name='uq_assessment_emp_date')
    )
    op.create_index(op.f('ix_assessment_results_employee_id'), 'assessment_results', ['employee_id'], unique=False)
    op.create_table('compensation_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.String(length=100), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('pay_type', sa.String(length=20), nullable=False),
    sa.Column('fixed_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('bounty_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_compensation_emp_from', 'compensation_records', ['employee_id', 'effective_from'], unique=False)
    op.create_table('departments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('erp_department_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('head_employee_id', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('erp_department_id')
    )
    op.create_table('leech_flags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.String(length=100), nullable=False),
    sa.Column('flagged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('months_extended', sa.Integer(), nullable=False),
    sa.Column('growth_trajectory', sa.String(length=20), nullable=False),
    sa.Column('recommendation', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_leech_flags_emp_status', 'leech_flags', ['employee_id', 'status'], unique=False)
    op.create_table('skill_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.String(length=100), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_skill_history_emp_date', 'skill_history', ['employee_id', 'snapshot_date'], unique=False)
    op.create_table('stage_gate_flags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.String(length=100), nullable=False),
    sa.Column('from_stage', sa.String(length=50), nullable=False),
    sa.Column('gate_due_date', sa.Date(), nullable=False),
    sa.Column('flag_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stage_gate_flags_employee_resolved', 'stage_gate_flags', ['employee_id', 'resolved'], unique=False)
    op.create_table('stage_transitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.String(length=100), nullable=False),
    sa.Column('from_stage', sa.String(length=50), nullable=False),
    sa.Column('to_stage', sa.String(length=50), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('decided_by', sa.String(length=100), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stage_transitions_employee', 'stage_transitions', ['employee_id'], unique=False)
    op.create_table('stroma_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.String(length=100), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('triggered_by', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stroma_actions_created', 'stroma_actions', ['created_at'], unique=False)
    op.create_index('ix_stroma_actions_employee_type', 'stroma_actions', ['employee_id', 'action_type'], unique=False)
    op.create_table('capacity_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('headcount', sa.Integer(), nullable=False),
    sa.Column('bench_metrics', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_capacity_snapshots_dept_date', 'capacity_snapshots', ['department_id', 'snapshot_date'], unique=False)
    op.create_table('hiring_flags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('shortfall', sa.Integer(), nullable=False),
    sa.Column('graduating_soon', sa.Integer(), nullable=False),
    sa.Column('recommended_batch_size', sa.Integer(), nullable=False),
    sa.Column('hire_by_date', sa.Date(), nullable=False),
    sa.Column('urgency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('flagged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hiring_flags_dept_status', 'hiring_flags', ['department_id', 'status'], unique=False)
    op.create_table('people',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slack_user_id', sa.String(length=100), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('capacity_hours_per_week', sa.Float(), nullable=False),
    sa.Column('hourly_rate_usd', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('current_stage', sa.String(length=50), nullable=False),
    sa.Column('join_date', sa.Date(), nullable=False),
    sa.Column('stage_start_date', sa.Date(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('exit_date', sa.Date(), nullable=True),
    sa.Column('exit_reason', sa.String(length=50), nullable=True),
    sa.Column('outside_hire', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("current_stage IN ('intern_bounty','intern_hybrid','full_time','apm','tech_lead','pm','dept_head')", name='ck_people_current_stage'),
    sa.CheckConstraint("exit_reason IN ('graduated_let_go','voluntary_exit','converted','extended') OR exit_reason IS NULL", name='ck_people_exit_reason'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_people_active'), 'people', ['active'], unique=False)
    op.create_index('ix_people_dept_active', 'people', ['department_id', 'active'], unique=False)
    op.create_index(op.f('ix_people_employee_id'), 'people', ['employee_id'], unique=True)
    op.create_table('assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assignment_id', sa.String(length=100), nullable=False),
    sa.Column('employee_id', sa.String(length=100), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('hours_per_week', sa.Float(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['people.employee_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignments_assignment_id'), 'assignments', ['assignment_id'], unique=True)
    op.create_index('ix_assignments_employee_end', 'assignments', ['employee_id', 'end_date'], unique=False)
    op.create_table('bounties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bounty_id', sa.String(length=100), nullable=False),
    sa.Column('employee_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hours_estimated', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.CheckConstraint("status IN ('completed','in_progress','not_started','overdue')", name='ck_bounties_status'),
    sa.ForeignKeyConstraint(['employee_id'], ['people.employee_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bounties_bounty_id'), 'bounties', ['bounty_id'], unique=True)
    op.create_index('ix_bounties_employee_status', 'bounties', ['employee_id', 'status'], unique=False)
    op.create_table('growth_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.String(length=100), nullable=False),
    sa.Column('snapshot_month', sa.Date(), nullable=False),
    sa.Column('growth_score', sa.Integer(), nullable=False),
    sa.Column('growth_band', sa.String(length=20), nullable=False),
    sa.Column('growth_trajectory', sa.String(length=20), nullable=True),
    sa.Column('workforce_health', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['people.employee_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'snapshot_month', name='uq_growth_snapshots_emp_month')
    )
    op.create_index('ix_growth_snapshots_emp_month', 'growth_snapshots', ['employee_id', 'snapshot_month'], unique=False)
    op.create_table('leaves',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('leave_id', sa.String(length=100), nullable=False),
    sa.Column('employee_id', sa.String(length=100), nullable=False),
    sa.Column('leave_type', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['people.employee_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_leaves_employee_dates', 'leaves', ['employee_id', 'start_date', 'end_date'], unique=False)
    op.create_index(op.f('ix_leaves_leave_id'), 'leaves', ['leave_id'], unique=True)
    op.create_table('skill_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.String(length=100), nullable=False),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['people.employee_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_profiles_employee_id'), 'skill_profiles', ['employee_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skill_profiles_employee_id'), table_name='skill_profiles')
    op.drop_table('skill_profiles')
    op.drop_index(op.f('ix_leaves_leave_id'), table_name='leaves')
    op.drop_index('ix_leaves_employee_dates', table_name='leaves')
    op.drop_table('leaves')
    op.drop_index('ix_growth_snapshots_emp_month', table_name='growth_snapshots')
    op.drop_table('growth_snapshots')
    op.drop_index('ix_bounties_employee_status', table_name='bounties')
    op.drop_index(op.f('ix_bounties_bounty_id'), table_name='bounties')
    op.drop_table('bounties')
    op.drop_index('ix_assignments_employee_end', table_name='assignments')
    op.drop_index(op.f('ix_assignments_assignment_id'), table_name='assignments')
    op.drop_table('assignments')
    op.drop_index(op.f('ix_people_employee_id'), table_name='people')
    op.drop_index('ix_people_dept_active', table_name='people')
    op.drop_index(op.f('ix_people_active'), table_name='people')
    op.drop_table('people')
    op.drop_index('ix_hiring_flags_dept_status', table_name='hiring_flags')
    op.drop_table('hiring_flags')
    op.drop_index('ix_capacity_snapshots_dept_date', table_name='capacity_snapshots')
    op.drop_table('capacity_snapshots')
    op.drop_index('ix_stroma_actions_employee_type', table_name='stroma_actions')
    op.drop_index('ix_stroma_actions_created', table_name='stroma_actions')
    op.drop_table('stroma_actions')
    op.drop_index('ix_stage_transitions_employee', table_name='stage_transitions')
    op.drop_table('stage_transitions')
    op.drop_index('ix_stage_gate_flags_employee_resolved', table_name='stage_gate_flags')
    op.drop_table('stage_gate_flags')
    op.drop_index('ix_skill_history_emp_date', table_name='skill_history')
    op.drop_table('skill_history')
    op.drop_index('ix_leech_flags_emp_status', table_name='leech_flags')
    op.drop_table('leech_flags')
    op.drop_table('departments')
    op.drop_index('ix_compensation_emp_from', table_name='compensation_records')
    op.drop_table('compensation_records')
    op.drop_index(op.f('ix_assessment_results_employee_id'), table_name='assessment_results')
    op.drop_table('assessment_results')
    # ### end Alembic commands ###